name: Up to date

on:
  push:
    branches:
      - 'main'

jobs:
  updatePullRequests:
    name: Keep PRs up to date
    runs-on: ubuntu-latest
    steps:
      - name: Update all the PRs
        uses: paritytech/up-to-date-action@main
        with:
          GITHUB_TOKEN: ${{ github.token }}
